# Generated by Django 6.0.2 on 2026-02-17 18:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Код кампании')),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(max_length=50, verbose_name='Код бокса')),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Длина, м')),
                ('width_m', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ширина, м')),
                ('height_m', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Высота, м')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
                'ordering': ['warehouse__title', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(default='Согласие на обработку персональных данных', max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/privacy/', verbose_name='PDF')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Документ ПД',
                'verbose_name_plural': 'Документы ПД',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Код')),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Скидка, %')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(verbose_name='Конец')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('rule_type', models.CharField(choices=[('allowed', 'Разрешено'), ('forbidden', 'Запрещено')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Пункт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Правило хранения',
                'verbose_name_plural': 'Правила хранения',
                'ordering': ['sort_order', 'rule_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('city', models.CharField(default='Москва', max_length=120, verbose_name='Город')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('work_hours', models.CharField(blank=True, default='Ежедневно 9:00–21:00', max_length=120, verbose_name='Часы работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['city', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Начало аренды')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец аренды')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('overdue', 'Просрочена'), ('closed', 'Закрыта'), ('lost', 'Потеряна (не забрали 6 месяцев)')], default='active', max_length=20, verbose_name='Статус')),
                ('pickup_from_home', models.BooleanField(default=True, verbose_name='Бесплатный вывоз из дома')),
                ('pickup_address', models.CharField(blank=True, max_length=300, verbose_name='Адрес забора')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Имя для связи')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='Телефон для связи')),
                ('personal_data_consent', models.BooleanField(default=False, verbose_name='Согласие на ПД')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Токен доступа')),
                ('overdue_grace_months', models.PositiveSmallIntegerField(default=6, verbose_name='Месяцев хранения после срока')),
                ('base_price_per_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена/мес без скидки')),
                ('final_price_per_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена/мес со скидкой')),
                ('ad_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.adcampaign', verbose_name='Кампания')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='storage.box', verbose_name='Бокс')),
                ('consent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.privacypolicydocument', verbose_name='Документ ПД')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('before_30', 'За 30 дней'), ('before_14', 'За 14 дней'), ('before_7', 'За 7 дней'), ('before_3', 'За 3 дня'), ('overdue_info', 'Просрочка: что будет'), ('overdue_monthly', 'Просрочка: ежемесячно'), ('pickup_qr', 'Выдача: QR'), ('partial_pickup_ok', 'Частичный вывоз разрешён')], max_length=30, verbose_name='Тип')),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Кому')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='storage.rental', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Email-уведомление',
                'verbose_name_plural': 'Email-уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('from_address', models.CharField(blank=True, max_length=300, verbose_name='Откуда')),
                ('to_address', models.CharField(blank=True, max_length=300, verbose_name='Куда')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tasks', to='storage.rental', verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Задача доставки',
                'verbose_name_plural': 'Задачи доставки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storage.warehouse', verbose_name='Склад'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['status', 'end_date'], name='storage_ren_status_7dc9d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='box',
            unique_together={('warehouse', 'code')},
        ),
    ]
