# Generated by Django 6.0.2 on 2026-02-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='warehouses/', verbose_name='Фото склада'),
        ),
    ]
