# Generated by Django 6.0.2 on 2026-02-19 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_warehouse_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCalculationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('source', models.CharField(choices=[('hero', 'Форма на первом экране'), ('promo', 'Форма в промо-блоке'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Источник')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('ad_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.adcampaign', verbose_name='Кампания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.warehouse', verbose_name='Склад (на странице)')),
            ],
            options={
                'verbose_name': 'Заявка на расчет',
                'verbose_name_plural': 'Заявки на расчет',
                'ordering': ['-created_at'],
            },
        ),
    ]
