# Generated by Django 6.0.2 on 2026-02-20 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_pricecalculationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Код')),
                ('target_path', models.CharField(default='/', help_text='Например: / или /boxes/', max_length=200, verbose_name='Куда ведёт')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Переходы')),
                ('ad_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='storage.adcampaign', verbose_name='Рекламная кампания')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
