# Generated by Django 6.0.1 on 2026-02-23 21:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_shortlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='ceiling_height',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.50'), max_digits=4, verbose_name='Высота потолка, м'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='temperature',
            field=models.IntegerField(default=18, verbose_name='Температура, °С'),
        ),
    ]
